###############################
# AI Tanks Configuration File #
###############################

[server]
# Listen address is either a specific address or any.
listen_address=any
# Listen port is the UDP port number to listen to
listen_port=1234

[game]
# Number of tiles in width on the field for tanks to compete in
field_width=12
# Number of tiles in height on the field for tanks to compete in
field_height=12
# Maximum number of players who can compete at a time
player_max=8


# Player Health.  How much they can achieve and how much they start with.
health_max=3
health_starting=2
# Number of times a player waits until they can repair one missing health
repair_waits=10

# Number of seconds after a move before the next move can be taken
move_cooldown=1
# Number of seconds to wait after a scan
scan_cooldown=1
# Number of seconds to wait after a extended scan
extended_cooldown=2
